name: "Create PR To Production"

on:
  push:
    branches:
      - 'staging/**'

jobs:
  create_pr:
    runs-on: ubuntu-latest
    steps:
      - name: Create New PR
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh pr create --base production --head ${{ github.ref_name }} --title "本番リリース" --body ""
