name: "Create Staging Branch"

on:
  push:
    branches:
      - main
  paths-ignore:
    - '*.md'

jobs:
  create_branch:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set BRANCH_NAME Env
        env:
          TZ: 'Asia/Tokyo'
        run: echo "BRANCH_NAME=staging/$(date +'%Y%m%d%H%M%S')" >> $GITHUB_ENV
      - name: Create new branch
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git switch -C ${{ env.BRANCH_NAME }}
          git push -u origin ${{ env.BRANCH_NAME }}

