name: "Merged To Production Branch"

on:
  pull_request:
    branches:
      - production
    types:
      - closed

jobs:
  delete-staging-branch:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Delete staging branch
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git push origin --delete ${{ github.head_ref }}
