name: "Merged To Beta Branch"

on:
  pull_request:
    branches:
      - beta
    types:
      - closed

jobs:
  create-draft-pr:
    if: github.event.pull_request.merged == true && github.head_ref != 'main'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Create draft branch
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh pr create --base main --head ${{ github.head_ref }} --title "${{ github.event.pull_request.title }}" --body "${{ github.event.pull_request.body }}" --draft
